### ISSUE TITLE
Face unlock after double tap on ambient display

### ISSUE THREAD

**Issue by Dynamotivation** [XJIOP/Oxygen-AOD-Mod#4]
Hi,
I wanted to ask if it is possible to activate the face unlock by double tapping the ambient display. Even when set to always use face unlock on the lockscreen it still requires a swipe to access it. Is this a feature addable to the app or is there a system setting im missing.
I'm on a OnePlus 7 Pro.

Thank you.

**Comment by zeroq9** [comment]
I have the same issue :(

**Comment by XJIOP** [comment]
I tried to fix it, but it is not possible due to Android system limitations.

**Comment by Dynamotivation** [comment]
I am not hugely into Android coding, much less accessibility stuff, so this might be a stupid idea:
I assume it currently works by simulating a power button press, but would it change anything if it simulated multiple ones, so turning the device off again instantly and then to the lock screen bypassing the ambient display?

**Comment by XJIOP** [comment]
> I am not hugely into Android coding, much less accessibility stuff, so this might be a stupid idea:
> I assume it currently works by simulating a power button press, but would it change anything if it simulated multiple ones, so turning the device off again instantly and then to the lock screen bypassing the ambient display?

This app can only turn on the screen, simulating a power button only possible on rooted devices.
