### ISSUE TITLE
Face unlock not working after proceeding to lock screen from the ambient display

### ISSUE THREAD

**Issue by zeroq9** [XJIOP/Oxygen-AOD-Mod#5]
This issue has been occuring since I updated my device to the Oxygen OS11 open beta. It won't let me unlock with my face unless I press the face unlock icon on my os(can see in the top left corner in the screenshot i attached) ![Screenshot_20210209-170642.jpg](https://user-images.githubusercontent.com/60327999/107391659-33990780-6af9-11eb-96c8-25b0f1bb6818.jpg)

**Comment by XJIOP** [comment]
seems like a similar problem #4
